# .github/workflows/generate-blog.yml
name: Generate Weekly Blog

on:
  schedule:
    - cron: '0 9 * * 5' # 毎週金曜の18時 (JST)
  workflow_dispatch:

jobs:
  generate-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Blog
        run: |
          curl -X POST https://my-crypto-tool.vercel.app/api/generate-blog \
            -H "x-api-key: ${{ secrets.BLOG_API_SECRET }}"
