name: Summarize News Cron

on:
  schedule:
    - cron: '0 23 * * *' # JSTの8時 = UTCの23時
  workflow_dispatch: # 手動でトリガーするオプションも追加

jobs:
  summarize-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run summarize-news API
        run: |
          curl -X POST https://my-crypto-tool.vercel.app/api/summarize-news
